#!/bin/sh
# 19.4 — Point-in-time restore from a base backup + archived WAL.
#
# This script does NOT touch the live cluster directly — it writes a fully
# recovered data directory at $RESTORE_DIR and tells you what to do next. The
# split is deliberate: PITR is a high-stakes operation; the operator should
# review the recovered dir, optionally start it standalone for inspection, then
# swap it in for the production data dir under a stopped db service.
#
# Usage (from inside the db-backup sidecar, which has psql + pg_basebackup tools):
#
#   sh /scripts/pitr-restore.sh <stamp> [recovery_target_time]
#
#   <stamp>                   the base-backup stamp to start from, e.g. 20260606T140000Z
#                             (find with: ls /backups/base/)
#   [recovery_target_time]    optional ISO timestamp to recover to; defaults to
#                             "latest" (the end of the archived WAL stream).
#                             Format: '2026-06-06 14:32:00 UTC'
#
# Output: a fully recovered data directory at ${RESTORE_DIR:-/backups/restore}.
# Inspection workflow lives in docs/BACKUP.md → "PITR".
set -eu

: "${ARCHIVE_DIR:=/var/lib/postgresql/archive}"
: "${BASE_DIR:=/backups/base}"
: "${RESTORE_DIR:=/backups/restore}"

stamp="${1:-}"
target_time="${2:-}"

if [ -z "$stamp" ]; then
    echo "usage: $0 <stamp> [recovery_target_time]"
    echo ""
    echo "available base backups:"
    [ -d "$BASE_DIR" ] && ls -1 "$BASE_DIR" | sort || echo "  (none)"
    exit 2
fi

base_src="${BASE_DIR}/${stamp}"
if [ ! -d "$base_src" ] || [ ! -f "${base_src}/base.tar.gz" ]; then
    echo "[restore] no base backup at ${base_src}/base.tar.gz"
    exit 1
fi

# Refuse to clobber a previous restore-in-progress — the operator must move it
# aside intentionally so we never destroy the only good copy of a recovery dir.
if [ -e "$RESTORE_DIR" ]; then
    echo "[restore] $RESTORE_DIR already exists. Move it aside first:"
    echo "    mv $RESTORE_DIR ${RESTORE_DIR}.$(date -u +%Y%m%dT%H%M%SZ)"
    exit 1
fi

echo "[restore] $(date -u +%FT%TZ) restoring base ${stamp} -> ${RESTORE_DIR}"
mkdir -p "$RESTORE_DIR"
tar -xzf "${base_src}/base.tar.gz" -C "$RESTORE_DIR"
# pg_wal contents from the base backup go under pg_wal/; archive replay tops up
# from there until the recovery target is hit.
if [ -f "${base_src}/pg_wal.tar.gz" ]; then
    mkdir -p "${RESTORE_DIR}/pg_wal"
    tar -xzf "${base_src}/pg_wal.tar.gz" -C "${RESTORE_DIR}/pg_wal"
fi

# Recovery configuration (Postgres 12+ uses postgresql.auto.conf + a
# recovery.signal file, NOT the legacy recovery.conf).
{
    echo "# Generated by pitr-restore.sh on $(date -u +%FT%TZ)"
    echo "restore_command = 'cp ${ARCHIVE_DIR}/%f %p'"
    if [ -n "$target_time" ]; then
        echo "recovery_target_time = '${target_time}'"
        # If a target is set, stop right at it (don't promote past it) so the
        # operator can decide whether to promote or pick a different time.
        echo "recovery_target_action = 'pause'"
    else
        echo "# No recovery_target_time set — replay all archived WAL, then promote."
    fi
} >> "${RESTORE_DIR}/postgresql.auto.conf"
touch "${RESTORE_DIR}/recovery.signal"

# Permissions: pg_basebackup produces files owned by whatever uid wrote the
# tarball; postgres refuses to start if PGDATA is group/world-readable. Also
# defensively chown to postgres in case we ran as root and tar untar'd as root.
chmod 700 "$RESTORE_DIR"
chown -R postgres:postgres "$RESTORE_DIR" 2>/dev/null || true

echo "[restore] data directory ready at ${RESTORE_DIR}"
echo "[restore] To finish recovery:"
echo "  1. Stop the live db service:           docker compose -f docker-compose.prod.yml stop db api web"
echo "  2. Move the live data dir aside:        docker compose ... exec -T db sh -c 'mv /var/lib/postgresql/data /var/lib/postgresql/data.swapout'"
echo "  3. Move recovered dir into place:       cp -a ${RESTORE_DIR}/. /var/lib/postgresql/data/"
echo "  4. Start db only:                       docker compose -f docker-compose.prod.yml start db"
echo "  5. Tail logs until 'database system is ready to accept connections'"
echo "     (if recovery_target_time was set, you may need to:    SELECT pg_wal_replay_resume();    then promote)"
echo "  6. Start api + web."
