/**
 * Type-only helpers over the auto-generated OpenAPI client (19.5).
 *
 * `lib/api-generated.d.ts` is produced from `api-spec/openapi.json` via
 * `npm run gen:api`. The runtime spec is regenerated by CI and compared against
 * the checked-in snapshot — a drift fails the build, so a backend change that
 * isn't reflected here is impossible to merge.
 *
 * This module exposes terse aliases for two common shapes:
 *   - `ApiResponse<"/api/x", "get">`     → the 200 JSON body of GET /api/x
 *   - `ApiRequestBody<"/api/x", "post">` → the JSON body POSTed to /api/x
 *   - `components["schemas"]["XxxDto"]`  → a DTO schema by name (when you need
 *      one independent of a particular endpoint, e.g. for table row shapes).
 *
 * Existing hand-written types in `lib/types.ts` remain — this PR is incremental:
 * new call sites should use the generated types; legacy ones get migrated as the
 * code they touch is edited. Drift between the two is caught by tsc on every
 * touchpoint.
 */
import type { paths, components } from "./api-generated"

/** All schema components by name, e.g. `Schema<"BidRegisterRow">`. */
export type Schema<K extends keyof components["schemas"]> = components["schemas"][K]

/** The 200 JSON body of a given (path, method) operation. */
export type ApiResponse<P extends keyof paths, M extends keyof paths[P]> =
  paths[P][M] extends { responses: { 200: { content: { "application/json": infer T } } } }
    ? T
    : never

/** The JSON request body of a given (path, method) operation (or `never` when none). */
export type ApiRequestBody<P extends keyof paths, M extends keyof paths[P]> =
  paths[P][M] extends { requestBody: { content: { "application/json": infer T } } }
    ? T
    : never

export type { paths, components }
